- name: Update Base System
  apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Install tools required to setup the system
  apt:
    name:
    - make
    - zsh
    - gpg
    state: latest

- name: Add signing key to keyring
  shell: |
    gpg --keyserver hkps://keys.openpgp.org --recv-keys {{ signing_key }}
