- name: Update Base System
  apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Install tools required to setup the system
  apt:
    name:
    - make
    - zsh
    - gpg
    state: latest
