server:
	ansible-playbook ./environments/server.yml -i ./inventory-test  -b -u a -v

desktop:
	ansible-playbook ./environments/desktop.yml -i ./inventory-test  -b -u a -v

desktop-vm:
	ansible-playbook ./environments/desktop-vm.yml -i ./inventory-test  -b -u a -v

